#!/usr/bin/python3
import sys

def factorize(number):
    factors = []
    for i in range(2, number // 2 + 1):
        while number % i == 0:
            factors.append(i)
            number //= i
    if number > 1:
        factors.append(number)
    return factors

def main(filename):
    try:
        with open(filename, 'r') as file:
            lines = file.read().splitlines()
            for line in lines:
                number = int(line)
                factors = factorize(number)
                print(f"{number}={'*'.join(map(str, factors))}")
    except FileNotFoundError:
        print(f"File '{filename}' does not exist.")
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python factors.py <file>")
    else:
        main(sys.argv[1])
